spring:
    application:
        name: 'ontopop'
        version: '3.0.0'
    jackson:
        serialization:
            write_dates_as_timestamps: false
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    servlet:
        multipart:
            enabled: true
            location: ${java.io.tmpdir}
            max-file-size: 1024KB
            max-request-size: 1024KB
security:
    authentication:
        api:
            enabled: true
            jwt:
                secretKey: ''
                username: ''
                issuer: ''
web:
    client:
        codecs:
            maxInMemorySize: 10
    aws:
        beanstalk:
            port: 5000
springdoc:
    api-docs:
        path: /docs