spring:
    application:
        name: 'ontopop'
        version: '3.0.0'
    jackson:
        serialization:
            write_dates_as_timestamps: false
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
    servlet:
        multipart:
            enabled: true
            location: ${java.io.tmpdir}
            max-file-size: 1024KB
            max-request-size: 1024KB
security:
    api:
        enabled: ${API_AUTH_ENABLED}
        jwt:
            secretKey: ${JWT_SECRET_KEY}
            username: ${JWT_USERNAME}
            issuer: ${JWT_ISSUER}
    cors:
        enabled: ${CORS_ENABLED}
        allowedOrigins: ${CORS_ALLOWED_ORIGINS}
web:
    client:
        codecs:
            maxInMemorySize: 10
    aws:
        beanstalk:
            port: 5000