spring:
    application:
        name: ontopop
    cloud:
        stream:
            bindings:
                ontologyIngestedChannel:
                    destination: ontopop.ontology.ingested
                    binder: local_rabbit
                ontologyValidatedChannel:
                    destination: ontopop.ontology.validated
                    binder: local_rabbit
                ontologyParsedChannel:
                    destination: ontopop.ontology.parsed
                    binder: local_rabbit
                ontologyModelledChannel:
                    destination: ontopop.ontology.modelled
                    binder: local_rabbit
                ontologyLoadedChannel:
                    destination: ontopop.ontology.loaded
                    binder: local_rabbit
            binders:
                local_rabbit:
                    type: rabbit
                    environment:
                        spring:
                            rabbitmq:
                                host: ${rabbitmq.host}
                                port: ${rabbitmq.port}
                                username: ${rabbitmq.username}
                                password: ${rabbitmq.password}
                                virtual-host: /
            default:
                contentType: application/json
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
security:
    vault:
        paths:
            subpaths:
                ontologies: /ontologies/
storage:
    object:
        service: aws-s3
        local:
            baseUri: ~/ontopop
        aws-s3:
            access-key-id: ${aws.s3.access-key-id}
            access-key-secret: ${aws.s3.access-key-secret}
            region: eu-west-2
            bucket-name: ontopop
        azure-storage:
            account-name: ${azure.storage.account-name}
            account-key: ${azure.storage.account-key}
            blob-endpoint: ${azure.storage.blob-endpoint}
            container-name: ontopop
        dirNames:
            ingested: ingested
            validated: validated
            parsed: parsed
        patterns:
            fileNameIdsSeparator: "_"
web:
    client:
        codecs:
            maxInMemorySize: 10
