spring:
    application:
        name: ontopop
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
security:
    vault:
        paths:
            subpaths:
                ontologies: /ontologies/
storage:
    file:
        service: azure-storage
        local:
            baseUri: ~/ontopop
        azure-storage:
            account-name: ${azure.storage.account-name}
            account-key: ${azure.storage.account-key}
            blob-endpoint: ${azure.storage.blob-endpoint}
            container-name: ${azure.storage.container-name}
        dirNames:
            ingested: ingested
            validated: validated
            parsed: parsed
        patterns:
            fileNameIdsSeparator: "_"
web:
    client:
        codecs:
            maxInMemorySize: 10
