spring:
    application:
        name: ontopop
    cloud:
        stream:
            binders:
                rabbitmq:
                    type: rabbit
                    default-candidate: true
                    environment:
                        spring:
                            rabbitmq:
                                host: ${rabbitmq-host}
                                port: ${rabbitmq-port}
                                username: ${rabbitmq-username}
                                password: ${rabbitmq-password}
                                virtual-host: /
                                ssl:
                                    enabled: false
                azure_service_bus:
                    type: servicebus-topic
                    default-candidate: false
                    environment:
                        spring:
                            cloud:
                                azure:
                                    servicebus:
                                        connection-string: ${azure-service-bus-connection-string}
            bindings:
                ingestedPublicationChannel:
                    destination: ontopop.data.ingested
                    binder: rabbitmq
                ingestedConsumptionChannel:
                    destination: ontopop.data.ingested
                    group: ontopop.data.ingested.consumers
                    binder: rabbitmq
                validatedPublicationChannel:
                    destination: ontopop.data.validated
                    binder: rabbitmq
                validatedTriplestoreLoaderConsumptionChannel:
                    destination: ontopop.data.validated
                    group: ontopop.data.validated.consumers.loaders.rdf
                    binder: rabbitmq
                validatedParserConsumptionChannel:
                    destination: ontopop.data.validated
                    group: ontopop.data.validated.consumers.parsers
                    binder: rabbitmq
                triplestoreLoadedPublicationChannel:
                    destination: ontopop.data.loaded.triplestore
                    binder: rabbitmq
                triplestoreLoadedConsumptionChannel:
                    destination: ontopop.data.loaded.triplestore
                    group: ontopop.data.loaded.triplestore.consumers
                    binder: rabbitmq
                parsedPublicationChannel:
                    destination: ontopop.data.parsed
                    binder: rabbitmq
                parsedConsumptionChannel:
                    destination: ontopop.data.parsed
                    group: ontopop.data.parsed.consumers
                    binder: rabbitmq
                modelledPublicationChannel:
                    destination: ontopop.data.modelled
                    binder: rabbitmq
                modelledGraphLoaderConsumptionChannel:
                    destination: ontopop.data.modelled
                    group: ontopop.data.modelled.consumers.loaders.graph
                    binder: rabbitmq
                modelledGraphIndexerConsumptionChannel:
                    destination: ontopop.data.modelled
                    group: ontopop.data.modelled.consumers.indexers.graph
                    binder: rabbitmq
                graphLoadedPublicationChannel:
                    destination: ontopop.data.loaded.graph
                    binder: rabbitmq
                graphLoadedConsumptionChannel:
                    destination: ontopop.data.loaded.graph
                    group: ontopop.data.loaded.graph.consumers
                    binder: rabbitmq
                graphIndexedPublicationChannel:
                    destination: ontopop.data.indexed.graph
                    binder: rabbitmq
                graphIndexedConsumptionChannel:
                    destination: ontopop.data.indexed.graph
                    group: ontopop.data.indexed.graph.consumers
                    binder: rabbitmq
            servicebus:
                topic:
                    bindings:
                        ingestedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        validatedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        parsedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        modelledLoadersConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        modelledIndexersConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        modelledLoadedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        modelledIndexedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
                        validatedLoadedConsumptionChannel:
                            consumer:
                                checkpoint-mode: MANUAL
            function:
                definition: consume;supply;
            poller:
                fixed-delay: 1000
                initial-delay: 0
            default:
                contentType: application/json
        vault:
            enabled: true
            host: localhost
            port: 8200
            scheme: http
            authentication: TOKEN
            token: ${VAULT_TOKEN}
            kv:
                enabled: true
                backend: secret
                default-context: ontopop/development
    datasource:
        driver-class-name: ${spring-datasource-driver-class-name}
        url: ${spring-datasource-url}
        username: ${spring-datasource-username}
        password: ${spring-datasource-password}
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
security:
    secrets:
        service: hashicorp-vault
        aws-secrets-manager: 
            access-key-id: ${aws-secrets-manager-access-key-id}
            access-key-secret: ${aws-secrets-manager-access-key-secret}
            region: eu-west-2
        azure-key-vault:
            url: ${azure-key-vault-url}
            clientId: ${azure-key-vault-client-id}
            clientSecret: ${azure-key-vault-client-secret}
            tenantId: ${azure-key-vault-tenant-id}
        hashicorp-vault:
            paths:
                subpaths:
                    ontologies: /ontologies/
storage:
    object:
        service: local
        local:
            baseUri: ${local-storage-base-directory-path}
        aws-s3:
            access-key-id: ${aws-s3-access-key-id}
            access-key-secret: ${aws-s3-access-key-secret}
            region: eu-west-2
            bucket-name: ontopop
        azure-storage:
            account-name: ${azure-storage-account-name}
            account-key: ${azure-storage-account-key}
            blob-endpoint: ${azure-storage-blob-endpoint}
            container-name: ontopop
        containers:
            ingested: ingested
            validated: validated
            parsed: parsed
            modelled: modelled
            loaded:
                triplestore: loaded/triplestore
                graph: loaded/graph
            indexed: indexed
    triplestore:
        service: apache-jena
        apache-jena:
            fuseki:
                url: ${jena-fuseki-url}
                username: ${jena-fuseki-username}
                password: ${jena-fuseki-password}
        ontotext-graphdb:
            url: ${ontotext-graphdb-url}
    graph:
        service: janusgraph-http
        engine:
            supportsUserDefinedIds: false
            supportsNonStringIds: true
            supportsSchema: true
            supportsTransactions: true
            supportsGeoshape: true
            supportsTraversals:
                by: true
        gremlin-graph:
            configuration-filename: gremlin-graph.properties
        gremlin-server:
            url: 
            host: ${gremlin-server-host}
            port: ${gremlin-server-port}
            username: ${gremlin-server-username}
            password: ${gremlin-server-password}
            enableSsl: false
            remoteTraversalSourceName: g
            serializer:
                className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1
                ioRegistries: org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry
                serializeResultToString: false
            bulkExecutor:
                rateLimiter:
                    enabled: false
                    actionsPerSecond: 100
                    maximumAttempts: 10
    search:
        service: elasticsearch
        indexNamePrefix: ontopop
        elasticsearch:
            url: ${elasticsearch-url}
            shards: 1
            replicas: 0
        azure-search:
            endpoint: ${azure-search-endpoint}
            key: ${azure-search-key}
web:
    client:
        codecs:
            maxInMemorySize: 10
    azure:
        webapps:
            port: 80
springdoc:
    api-docs:
        path: /api/docs
