spring:
    application:
        name: ontopop
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
security:
    vault:
        paths:
            subpaths:
                ontologies: /ontologies/
storage:
    object:
        service: aws-s3
        local:
            baseUri: ~/ontopop
        aws-s3:
            access-key-id: ${aws.s3.access-key-id}
            access-key-secret: ${aws.s3.access-key-secret}
            region: eu-west-2
            bucket-name: ontopop
        azure-storage:
            account-name: ${azure.storage.account-name}
            account-key: ${azure.storage.account-key}
            blob-endpoint: ${azure.storage.blob-endpoint}
            container-name: ontopop
        dirNames:
            ingested: ingested
            validated: validated
            parsed: parsed
        patterns:
            fileNameIdsSeparator: "_"
web:
    client:
        codecs:
            maxInMemorySize: 10
