spring:
    application:
        name: ontopop
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
    jackson:
        serialization:
            write_dates_as_timestamps: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
security:
    vault:
        paths:
            subpaths:
                ontologies: /ontologies/
storage:
    file:
        service: local
        baseUri: ~/ontopop
        dirNames:
            ingested: ingested
            validated: validated
            parsed: parsed
        patterns:
            fileNameIdsSeparator: "_"
