server:
    port: 8801
spring:
    application:
        name: ontopop-config-server
    cloud:
        config:
            server:
                native:
                    search-locations: file://${user.home}/ontopop/ontopop-config
    profiles:
        active: native
    security:
        user:
            name: 
            password: 